### PR TITLE
fixes setLang to handle navigator.language formats (such as "fr-FR")

### LINKED ISSUE #1472: setLang works with "fr" but not "fr-FR"
I use `navigator.language` which can return values likes "en", "en-US", "fr", "fr-FR", "es-ES", etc.

It seems calling `setLang` using the 2 letter value like "fr" works, but not the 5 letter value like "fr-FR". There should be a fallback from "fr-FR" to "fr", "es-ES" to "es", ...Basically just keeping the 1st 2 letters should fix it.

### PR DESCRIPTION
**Pull request by mscno**
closes #1472

### CODE REVIEW

File: src/assets/translations/index.js [hunk 1]
```diff
@@ -39,6 +42,7 @@ export default {
   es,
   nl,
   fr,
+  pt,
```
Comment (Falke-Design) [inline src/assets/translations/index.js:45]: we should add this in the typescript file too

**Review by Falke-Design — CHANGES_REQUESTED** [review]

**Review by mscno — COMMENTED** [review]
great!

**Review by Falke-Design — APPROVED** [review]
